#!/bin/sh

# Register the icons needed for ZAP and the OWASP menu
xdg-icon-resource install --size 64 /tmp/owasp-wte-zap/owasp-wte-menu-icon.png owasp-wte-menu-icon
xdg-icon-resource install --size 64 /tmp/owasp-wte-zap/owasp-wte-zap-icon.png owasp-wte-zap-icon 

# Create the necessary menu entries
xdg-desktop-menu install /tmp/owasp-wte-zap/owasp-owasp.directory \
                         /tmp/owasp-wte-zap/owasp-proxies.directory \
                         /tmp/owasp-wte-zap/owasp-wte-zap.desktop

# Cleanup /tmp
rm -rf /tmp/owasp-wte-zap

# Ensure the version of Java is set to Java 7
update-java-alternatives --set java-1.7.0-openjdk-i386

