#!/bin/sh

# Register the icons needed for WebScarab and the OWASP menu
xdg-icon-resource install --size 64 /tmp/owasp-wte-webscarab/owasp-wte-menu-icon.png owasp-wte-menu-icon
xdg-icon-resource install --size 64 /tmp/owasp-wte-webscarab/owasp-wte-webscarab-icon.png owasp-wte-webscarab-icon 

# Create the necessary menu entries
xdg-desktop-menu install /tmp/owasp-wte-webscarab/owasp-owasp.directory \
                         /tmp/owasp-wte-webscarab/owasp-proxies.directory \
                         /tmp/owasp-wte-webscarab/owasp-wte-webscarab.desktop

# Cleanup /tmp
rm -rf /tmp/owasp-wte-webscarab
