#!/bin/sh

# Register the icons needed for Paros and the OWASP menu
xdg-icon-resource install --size 64 /tmp/owasp-wte-paros/owasp-wte-menu-icon.png owasp-wte-menu-icon
xdg-icon-resource install --size 64 /tmp/owasp-wte-paros/owasp-wte-paros-icon.png owasp-wte-paros-icon 

# Create the necessary menu entries
xdg-desktop-menu install /tmp/owasp-wte-paros/owasp-owasp.directory \
                         /tmp/owasp-wte-paros/owasp-proxies.directory \
                         /tmp/owasp-wte-paros/owasp-wte-paros.desktop

# Cleanup /tmp
rm -rf /tmp/owasp-wte-paros
