#!/bin/sh

# Register the icons needed for tcpdump and the OWASP menu
xdg-icon-resource install --size 64 /tmp/owasp-wte-tcpdump/owasp-wte-menu-icon.png owasp-wte-menu-icon
xdg-icon-resource install --size 64 /tmp/owasp-wte-tcpdump/owasp-wte-tcpdump-icon.png owasp-wte-tcpdump-icon 

# Create the necessary menu entries
xdg-desktop-menu install /tmp/owasp-wte-tcpdump/owasp-owasp.directory \
                         /tmp/owasp-wte-tcpdump/owasp-wte-tcpdump.desktop

# Cleanup /tmp
rm -rf /tmp/owasp-wte-tcpdump
