#!/bin/sh

### Run special install from tarball script
/opt/owasp/w3af/get-w3af

# Register the icons needed for w3af and the OWASP menu
xdg-icon-resource install --size 64 /tmp/owasp-wte-w3af/owasp-wte-menu-icon.png owasp-wte-menu-icon
xdg-icon-resource install --size 64 /tmp/owasp-wte-w3af/owasp-wte-w3af-icon.png owasp-wte-w3af-icon 

# Create the necessary menu entries
# w3af-gui
xdg-desktop-menu install /tmp/owasp-wte-w3af/owasp-owasp.directory \
                         /tmp/owasp-wte-w3af/owasp-scanners.directory \
                         /tmp/owasp-wte-w3af/owasp-wte-w3af.desktop
# w3af-console
xdg-desktop-menu install /tmp/owasp-wte-w3af/owasp-owasp.directory \
                         /tmp/owasp-wte-w3af/owasp-scanners.directory \
                         /tmp/owasp-wte-w3af/owasp-wte-w3af-console.desktop

# Cleanup /tmp
rm -rf /tmp/owasp-wte-w3af
