#!/bin/sh

# Register the icons needed for Ratproxy and the OWASP menu
xdg-icon-resource install --size 64 /tmp/owasp-wte-ratproxy/owasp-wte-menu-icon.png owasp-wte-menu-icon
xdg-icon-resource install --size 64 /tmp/owasp-wte-ratproxy/owasp-wte-ratproxy-icon.png owasp-wte-ratproxy-icon 

# Create the necessary menu entries
xdg-desktop-menu install /tmp/owasp-wte-ratproxy/owasp-owasp.directory \
                         /tmp/owasp-wte-ratproxy/owasp-proxies.directory \
                         /tmp/owasp-wte-ratproxy/owasp-wte-ratproxy.desktop

# Cleanup /tmp
rm -rf /tmp/owasp-wte-ratproxy
