#!/bin/sh

# Register the icons needed for Firefox WTE Style and the OWASP menu
xdg-icon-resource install --size 64 /tmp/owasp-wte-firefox/owasp-wte-menu-icon.png owasp-wte-menu-icon
xdg-icon-resource install --size 64 /tmp/owasp-wte-firefox/owasp-wte-firefox-icon.png owasp-wte-firefox-icon 

# Create the necessary menu entries
xdg-desktop-menu install /tmp/owasp-wte-firefox/owasp-owasp.directory \
                         /tmp/owasp-wte-firefox/owasp-wte-firefox.desktop

# Cleanup /tmp
rm -rf /tmp/owasp-wte-firefox
