#!/bin/sh

# Register the icons needed for SQLBrute and the OWASP menu
xdg-icon-resource install --size 64 /tmp/owasp-wte-sqlbrute/owasp-wte-menu-icon.png owasp-wte-menu-icon
xdg-icon-resource install --size 64 /tmp/owasp-wte-sqlbrute/owasp-wte-sqlbrute-icon.png owasp-wte-sqlbrute-icon 

# Create the necessary menu entries
xdg-desktop-menu install /tmp/owasp-wte-sqlbrute/owasp-owasp.directory \
                         /tmp/owasp-wte-sqlbrute/owasp-scanners.directory \
                         /tmp/owasp-wte-sqlbrute/owasp-wte-sqlbrute.desktop

# Cleanup /tmp
rm -rf /tmp/owasp-wte-sqlbrute
