#!/bin/sh

# Register the icons needed for w3af-console and the OWASP menu
xdg-icon-resource install --size 64 /tmp/owasp-wte-w3af-console/owasp-wte-menu-icon.png owasp-wte-menu-icon
xdg-icon-resource install --size 64 /tmp/owasp-wte-w3af-console/owasp-wte-w3af-console-icon.png owasp-wte-w3af-console-icon 

# Create the necessary menu entries
xdg-desktop-menu install /tmp/owasp-wte-w3af-console/owasp-owasp.directory \
                         /tmp/owasp-wte-w3af-console/owasp-scanners.directory \
                         /tmp/owasp-wte-w3af-console/owasp-wte-w3af-console.desktop

# Cleanup /tmp
rm -rf /tmp/owasp-wte-w3af-console
