#!/bin/sh

# Register the icons needed for wsfuzzer and the OWASP menu
xdg-icon-resource install --size 64 /tmp/owasp-wte-wsfuzzer/owasp-wte-menu-icon.png owasp-wte-menu-icon
xdg-icon-resource install --size 64 /tmp/owasp-wte-wsfuzzer/owasp-wte-wsfuzzer-icon.png owasp-wte-wsfuzzer-icon 

# Create the necessary menu entries
xdg-desktop-menu install /tmp/owasp-wte-wsfuzzer/owasp-owasp.directory \
                         /tmp/owasp-wte-wsfuzzer/owasp-fuzzer.directory \
                         /tmp/owasp-wte-wsfuzzer/owasp-wte-wsfuzzer.desktop

# Cleanup /tmp
rm -rf /tmp/owasp-wte-wsfuzzer
