#!/bin/sh

# Register the icons needed for Netcat and the OWASP menu
xdg-icon-resource install --size 64 /tmp/owasp-wte-netcat/owasp-wte-menu-icon.png owasp-wte-menu-icon
xdg-icon-resource install --size 64 /tmp/owasp-wte-netcat/owasp-wte-netcat-icon.png owasp-wte-netcat-icon 

# Create the necessary menu entries
xdg-desktop-menu install /tmp/owasp-wte-netcat/owasp-owasp.directory \
                         /tmp/owasp-wte-netcat/owasp-wte-netcat.desktop

# Cleanup /tmp
rm -rf /tmp/owasp-wte-netcat
