#!/bin/sh

# Register the icons needed for Webslayer and the OWASP menu
xdg-icon-resource install --size 64 /tmp/owasp-wte-webslayer/owasp-wte-menu-icon.png owasp-wte-menu-icon
xdg-icon-resource install --size 64 /tmp/owasp-wte-webslayer/owasp-wte-webslayer-icon.png owasp-wte-webslayer-icon 

# Create the necessary menu entries
xdg-desktop-menu install /tmp/owasp-wte-webslayer/owasp-owasp.directory \
                         /tmp/owasp-wte-webslayer/owasp-fuzzer.directory \
                         /tmp/owasp-wte-webslayer/owasp-wte-webslayer.desktop

# Cleanup /tmp
rm -rf /tmp/owasp-wte-webslayer
