#!/bin/sh

# Register the icons needed for sqlmap and the OWASP menu
xdg-icon-resource install --size 64 /tmp/owasp-wte-sqlmap/owasp-wte-menu-icon.png owasp-wte-menu-icon
xdg-icon-resource install --size 64 /tmp/owasp-wte-sqlmap/owasp-wte-sqlmap-icon.png owasp-wte-sqlmap-icon 

# Create the necessary menu entries
xdg-desktop-menu install /tmp/owasp-wte-sqlmap/owasp-owasp.directory \
                         /tmp/owasp-wte-sqlmap/owasp-scanners.directory \
                         /tmp/owasp-wte-sqlmap/owasp-wte-sqlmap.desktop

# Cleanup /tmp
rm -rf /tmp/owasp-wte-sqlmap
